# Generated by Django 6.0.5 on 2026-06-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
